CREATE TABLE REQUESTS(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    MESSAGE TEXT NOT NULL,
    IP_ADDRESS INET NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    STATUS TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX idx_requests_ip_address ON REQUESTS(IP_ADDRESS);
CREATE INDEX idx_requests_status ON REQUESTS(STATUS);
